name: My First Workflow
on: workflow_dispatch
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v6

        - name: List and read file
          run: |
            echo "My first Github actions"
            ls -ltra
            cat README.md

        - name: Generate ASCII Artwork
          run: cowsay -f dragon "Run for cover, I a DRAGON....RAWR" >> dragon.txt

        # - name: List files
        #   run: ls

        # - name: Read file
        #   run: cat README.md
            
